#=============================================================================
#   >>   文件名: Makefile
#   >> 	   描述: 客户端makefile
#   >>     作者: wangbo
#   >>    Email: mawag@live.cn
#   >>	   主页: http://www.cnblogs.com/wangbo2008/
#   >>   Github: github.com/mawag
#   >> 程序版本: 0.0.1
#   >> 创建时间: 2014-08-15 10:38:21
#   >> 修改时间: 2014-08-15 10:38:21
#  Copyright (c) wangbo  All rights reserved.
#=============================================================================
main: c.c base64.h base64.c
	gcc -o c c.c base64.c -lpthread
clean:
	rm -f c
